server:
  port: 7923

spring:
  application:
    name: "redisson-delayed-queue-in-action"
  profiles:
    active: dev
  redis:
    host: ${local.config.redis.host}
    port: ${local.config.redis.port}
    password: ${local.config.redis.password}
    database: 0
    timeout: 2000
    serializer: "Generic"
    jedis:
      pool:
        max-idle: 6
        max-total: 32
        max-wait: 100
        min-idle: 4
    client:
      redisson:
        enabled: false
        mode: SINGLE
        address: "redis://${local.config.redis.host}:${local.config.redis.port}"
        password: "${local.config.redis.password}"
        master-name: "master"
        database: 0
        timeout: 10_000
        delayed:
          topic: "io.github.photowey:global:redisson:delayedqueue:topic"
          topics:
            - "io.github.photowey:hello:world:delayed:query:delayedqueue:topic"
          initial-delay: 0
          period: 1
          unit: "SECONDS"
          report:
            topic-set: "io.github.photowey:global:redisson:delayed:queue:topicset"
            task-set: "io.github.photowey:global:redisson:delayed:queue:taskset"

logging:
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'