---
--- Generated by Luanalysis
--- Created by photowey.
--- DateTime: 2021/10/27 15:15
---
if redis.call('get', KEYS[1]) == ARGV[1]
then
    return redis.call('pexpire', KEYS[1], ARGV[2])
else
    return 0
end