
package com.photowey.webservice.client.in.action.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 */
@WebServiceClient(name = "HelloWebServiceImplService", targetNamespace = "http://server.webservice.service.action.in.webservice.photowey.com", wsdlLocation = "http://localhost:7923/ws/hello?wsdl")
public class HelloWebServiceImplService
    extends Service {

    private final static URL HELLOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.webservice.service.action.in.webservice.photowey.com", "HelloWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7923/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWebServiceImplService() {
        super(__getWsdlLocation(), HELLOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HelloWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HelloWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns Hello
     */
    @WebEndpoint(name = "helloPort")
    public Hello getHelloPort() {
        return super.getPort(new QName("http://server.webservice.service.action.in.webservice.photowey.com", "helloPort"), Hello.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns Hello
     */
    @WebEndpoint(name = "helloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.service.action.in.webservice.photowey.com", "helloPort"), Hello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWEBSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw HELLOWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HELLOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
