server:
  port: 9527

# ----------------------------------------------------------------

spring:
  application:
    name: "jobrunr-in-action"
  profiles:
    active: dev
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    # ?useUnicode=true&characterEncoding=UTF-8
    # &zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    # &nullCatalogMeansCurrent=true
    url: "jdbc:mysql://${local.config.mysql.host}:${local.config.mysql.port}/${local.config.mysql.database}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true"
    username: ${local.config.mysql.username}
    password: ${local.config.mysql.password}

# ----------------------------------------------------------------

org:
  jobrunr:
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5
    dashboard:
      enabled: true

# ----------------------------------------------------------------

logging:
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n) %ex{20}'