server:
  port: 7923

# ----------------------------------------------------------------

spring:
  application:
    name: "webservice-server-in-action"
  profiles:
    active: dev

# ----------------------------------------------------------------

cxf:
  path: /ws

# ----------------------------------------------------------------

logging:
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'
