package io.github.photowey.drools.rules.helloworld;

import com.photowey.drools.in.action.core.domain.helloworld.Message;

global java.util.List list;

rule "io.github.photowey.drools.rule.helloworld"
    dialect "mvel"
    when
        $msg: Message( status == Message.HELLO, message: message )
    then
        System.out.println( message );
        modify($msg) {
            message = "Goodbye cruel world",
            status = Message.GOODBYE
        };
end

rule "io.github.photowey.drools.rule.goodbye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
end
