logging:
  level:
    root: INFO
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'

# ---------------------------------------------------------------------

spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:test_db"
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# ---------------------------------------------------------------------

io:
  github:
    photowey:
      infras:
        core:
          cache:
            loader: "database"
            expired: 60_000
            unit: MILLISECONDS